TRUNCATE TABLE PRODUCT;
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (1, 'Smartphone', 'High-end smartphone with advanced features', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (2, 'Laptop', 'Thin and light laptop with powerful performance', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (3, 'Smart TV', '4K Ultra HD Smart TV with built-in streaming apps', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (4, 'Wireless Earbuds', 'True wireless earbuds with noise cancellation', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (5, 'Gaming Console', 'Next-gen gaming console for immersive gaming experience', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (6, 'Tablet', 'Large screen tablet with long battery life', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (7, 'Smart Watch', 'Fitness tracker and smartwatch with heart rate monitoring', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (8, 'Camera', 'Professional DSLR camera with interchangeable lenses', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (9, 'Home Theater System', 'Surround sound system for cinematic experience at home', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (10, 'Drone', 'Quadcopter drone with 4K camera and GPS functionality', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (11, 'Gaming Mouse', 'High precision gaming mouse with customizable buttons.', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (12, 'Gaming Keyboard', 'Mechanical gaming keyboard with RGB lighting and programmable keys.', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (13, 'Gaming Headset', 'Immersive gaming headset with noise cancellation and surround sound.', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (14, 'Gaming Desk', 'Spacious gaming desk with cable management and RGB lighting.', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (15, 'Gaming Mousepad', 'Large gaming mousepad with smooth surface for precise movements.', TRUE);
INSERT INTO PRODUCT (ID, NAME, DESCRIPTION,STATUS) VALUES (16, 'Gaming Laptop', 'Powerful gaming laptop with dedicated graphics card and high-resolution display.', TRUE);
